### ISSUE TITLE
Wii support (boot.dol)

### ISSUE THREAD

**Issue by revvv** [Maschell/hid_test#1]
Does this run on Wii, too?
I had not luck with elf2dol: _Warning: writable and executable segment 0_
HBC reports "_this is not a valid wii application_"
I also tried to compile it myself, but boot.dol doesn't run, too.

I'd like to add Gamepad support to my homebrew app and I haven't found an example up to now.

**Comment by CreeperMario** [comment]
> I'd like to add Gamepad support to my homebrew app and I haven't found an example up to now.

I think you're looking for [this](https://github.com/FIX94/libwiidrc). `hid_test` is an app used to help generate configuration files for HID-to-VPAD, a Wii U plugin allowing USB controllers to be used in place of the GamePad/Wii U Pro Controller. None of the content in this repository is for the Wii or vWii.

**Comment by revvv** [comment]
Ok, thanks.
